// Curated collections: add TV show IDs or individual media IDs explicitly.
export const collections = [
  {
    id: 'princesses',
    title: 'Princesses',
    thumbnail: 'series/princesses.webp',
    description: 'Disney princess adventures, from classic fairy tales to Frozen and Moana.',
    showIds: [],
    mediaIds: [
      'snow-white-and-the-seven-dwarves', 'cinderella',
      'cinderella-ii-dreams-come-true', 'cinderella-iii-a-twist-in-time',
      'sleeping-beauty', 'the-little-mermaid',
      'the-little-mermaid-2-return-to-the-sea', 'the-little-mermaid-ariel-s-beginning',
      'beauty-and-the-beast', 'beauty-and-the-beast-the-enchanted-christmas',
      'belle-s-magical-world', 'aladdin', 'the-return-of-jafar',
      'aladdin-and-the-king-of-thieves', 'pocahontas',
      'pocahontas-ii-journey-to-a-new-world', 'mulan', 'mulan-ii',
      'disney-princess-enchanted-tales-follow-your-dreams', 'enchanted',
      'tangled', 'brave', 'frozen', 'frozen-2',
      'moana', 'moana-2', 'raya-and-the-last-dragon',
    ],
  },
  {
    id: 'studio-ghibli',
    title: 'Studio Ghibli',
    thumbnail: 'series/studio-ghibli.webp',
    description: 'Discover the worlds of Studio Ghibli and Nausicaä of the Valley of the Wind.',
    showIds: [],
    mediaIds: [
      'my-neighbor-totoro', 'from-up-on-poppy-hill', 'porco-rosso',
      'when-marnie-was-there', 'ponyo', 'kiki-s-delivery-service',
      'my-neighbors-the-yamadas', 'whisper-of-the-heart', 'tales-from-earthsea',
      'nausicaa-of-the-valley-of-the-wind', 'howl-s-moving-castle', 'pom-poko',
      'only-yesterday', 'laputa-castle-in-the-sky', 'spirited-away',
      'the-wind-rises', 'princess-mononoke',
    ],
  },
  {
    id: 'dc-universe',
    title: 'DC Universe',
    thumbnail: 'series/dc-universe.webp',
    description: 'Batman, Superman, and the Justice League.',
    showIds: [
      'batman-the-animated-series',
      'the-new-batman-adventures',
      'superman-the-animated-series',
      'max-fleischers-superman',
      'justice-league',
      'justice-league-unlimited',
    ],
    mediaIds: [
      'superman-brainiac-attacks',
      'superman-doomsday',
      'batman-mask-of-the-phantasm',
      'batman-mr-freeze-subzero',
      'the-lego-batman-movie',
    ],
  },
  {
    id: 'ice-age',
    title: 'Ice Age',
    thumbnail: 'series/ice-age.webp',
    description: 'Join Manny, Sid, and Diego on their prehistoric adventures.',
    showIds: [],
    mediaIds: [
      'ice-age',
      'ice-age-the-meltdown',
      'ice-age-dawn-of-the-dinosaurs',
      'ice-age-continental-drift',
      'ice-age-collision-course',
    ],
  },
  {
    id: 'sonic',
    title: 'Sonic',
    thumbnail: 'series/sonic.webp',
    description: 'Sonic and friends race into action across their shows and movie.',
    showIds: [
      'adventures-of-sonic-the-hedgehog',
      'sonic-the-hedgehog-satam',
      'sonic-underground',
      'sonic-x',
      'sonic-prime',
    ],
    mediaIds: ['sonic-the-hedgehog-ova'],
  },
  {
    id: 'toy-story',
    title: 'Toy Story',
    thumbnail: 'series/toy-story.webp',
    description: 'Join Woody, Buzz, and their friends on their toy-sized adventures.',
    showIds: [],
    mediaIds: [
      'toy-story',
      'toy-story-2',
      'toy-story-3',
      'toy-story-4',
      'toy-story-5',
      'buzz-lightyear-of-star-command-the-adventure-begins',
    ],
  },
  {
    id: 'cars-planes',
    title: 'Cars & Planes',
    thumbnail: 'series/cars-planes.webp',
    description: 'Lightning McQueen and Dusty take their racing dreams to the road and sky.',
    showIds: [],
    mediaIds: ['cars', 'cars-2', 'cars-3', 'planes'],
  },
  {
    id: 'peanuts',
    title: 'Peanuts',
    thumbnail: 'series/peanuts.webp',
    description: 'Charlie Brown, Snoopy, and friends in their specials, movie, history show, and documentary.',
    showIds: ['this-is-america-charlie-brown'],
    mediaIds: [
      'charlie-brown-christmas',
      'charlie-brown-christmastime-again',
      'charlie-brown-great-pumpkin',
      'charlie-brown-thanksgiving',
      'charlie-brown-its-magic',
      'charlie-brown-bon-voyage',
      'peanuts-we-need-a-blockbuster-charlie-brown',
    ],
  },
  {
    id: 'winnie-the-pooh',
    title: 'Winnie the Pooh',
    thumbnail: 'series/winnie-the-pooh.webp',
    description: 'Pooh, Tigger, and friends explore the Hundred Acre Wood and beyond.',
    showIds: [],
    mediaIds: [
      'the-many-adventures-of-winnie-the-pooh',
      'winnie-the-pooh-s-most-grand-adventure',
      'the-tigger-movie',
      'winnie-the-pooh',
    ],
  },
  {
    id: 'neverland',
    title: 'Neverland',
    thumbnail: 'series/neverland.webp',
    description: 'Peter Pan, Tinker Bell, and their adventures in Neverland.',
    showIds: [],
    mediaIds: [
      'peter-pan',
      'return-to-never-land',
      'tinker-bell',
      'tinker-bell-lost-treasure',
      'tinker-bell-great-fairy-rescue',
      'the-pirate-fairy',
    ],
  },
  {
    id: 'kung-fu-panda',
    title: 'Kung Fu Panda',
    thumbnail: 'series/kung-fu-panda.webp',
    description: 'Po and the Furious Five bring kung fu adventure to the big screen.',
    showIds: [],
    mediaIds: [
      'kung-fu-panda',
      'kung-fu-panda-2',
      'kung-fu-panda-3',
      'kung-fu-panda-4',
    ],
  },
]
