// Curated collections: add TV show IDs or individual media IDs explicitly.
export const collections = [
  {
    id: 'dc-universe',
    title: 'DC Universe',
    thumbnail: 'series/dc-universe.webp',
    description: 'Batman, Superman, and the Justice League.',
    showIds: [
      'batman-the-animated-series',
      'the-new-batman-adventures',
      'superman-the-animated-series',
      'max-fleischers-superman',
      'justice-league',
      'justice-league-unlimited',
    ],
    mediaIds: [
      'superman-brainiac-attacks',
      'superman-doomsday',
      'batman-mask-of-the-phantasm',
      'batman-mr-freeze-subzero',
    ],
  },
  {
    id: 'ice-age',
    title: 'Ice Age',
    thumbnail: 'series/ice-age.webp',
    description: 'Join Manny, Sid, and Diego on their prehistoric adventures.',
    showIds: [],
    mediaIds: [
      'ice-age',
      'ice-age-the-meltdown',
      'ice-age-dawn-of-the-dinosaurs',
      'ice-age-continental-drift',
      'ice-age-collision-course',
    ],
  },
  {
    id: 'sonic',
    title: 'Sonic',
    thumbnail: 'series/sonic.webp',
    description: 'Sonic and friends race into action across their shows and movie.',
    showIds: [
      'adventures-of-sonic-the-hedgehog',
      'sonic-the-hedgehog-satam',
      'sonic-underground',
      'sonic-x',
      'sonic-prime',
    ],
    mediaIds: ['sonic-the-hedgehog-ova'],
  },
  {
    id: 'toy-story',
    title: 'Toy Story',
    thumbnail: 'series/toy-story.webp',
    description: 'Join Woody, Buzz, and their friends on their toy-sized adventures.',
    showIds: [],
    mediaIds: [
      'toy-story',
      'toy-story-2',
      'toy-story-3',
      'toy-story-4',
      'toy-story-5',
    ],
  },
  {
    id: 'neverland',
    title: 'Neverland',
    thumbnail: 'series/neverland.webp',
    description: 'Peter Pan, Tinker Bell, and their adventures in Neverland.',
    showIds: [],
    mediaIds: [
      'peter-pan',
      'return-to-never-land',
      'tinker-bell',
      'tinker-bell-lost-treasure',
      'tinker-bell-great-fairy-rescue',
      'the-pirate-fairy',
    ],
  },
  {
    id: 'kung-fu-panda',
    title: 'Kung Fu Panda',
    thumbnail: 'series/kung-fu-panda.webp',
    description: 'Po and the Furious Five bring kung fu adventure to the big screen.',
    showIds: [],
    mediaIds: [
      'kung-fu-panda',
      'kung-fu-panda-2',
      'kung-fu-panda-3',
      'kung-fu-panda-4',
    ],
  },
]
