import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ClerkProvider, SignedIn, SignedOut, SignInButton, UserButton, useAuth, useReverification } from '@clerk/clerk-react'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faArrowLeft, faCheck, faChevronLeft, faChevronRight, faChild, faCircleInfo, faFaceSmile, faLock, faMagnifyingGlass, faPen, faPlay, faPlus, faTrashCan, faTriangleExclamation, faUsersGear, faXmark } from '@fortawesome/free-solid-svg-icons'
import './style.css'

const key=import.meta.env.VITE_CLERK_PUBLISHABLE_KEY
const api=import.meta.env.VITE_API_URL
const colors=['#e50914','#0f9d8f','#6b38d1','#1773e8','#e67e22','#27952c','#c2185b','#0086a8']
const genres=['Action','Adventure','Cartoon','Live Action','Animation','Family','Suspense','Science Fiction','Fantasy','Sports','Romance','Comedy','Home Videos']
function profileColor(profile){let value=0;for(const char of profile.id)value=(value*31+char.charCodeAt(0))>>>0;return colors[value%colors.length]}
function Avatar({profile,add=false}){return <span className={`avatar${add?' add-avatar':''}`} style={add?undefined:{'--avatar-color':profileColor(profile)}} aria-hidden="true">{add?<FontAwesomeIcon icon={faPlus}/>:<FontAwesomeIcon className="avatar-face" icon={faFaceSmile}/>}</span>}
function Logo(){return <img className="brand-logo" src={`${import.meta.env.BASE_URL}logo-kingflix.png`} alt="Kingflix"/>}

function App(){
  const{getToken}=useAuth()
  const[profiles,setProfiles]=useState([]),[profile,setProfile]=useState(null),[profileToken,setProfileToken]=useState('')
  const[view,setView]=useState('select'),[pending,setPending]=useState(null),[pin,setPin]=useState('')
  const[form,setForm]=useState({name:'',pin:'',isKids:false,removePin:false})
  const[media,setMedia]=useState([]),[progress,setProgress]=useState([]),[favorites,setFavorites]=useState([]),[selected,setSelected]=useState(null)
  const[error,setError]=useState(''),[busy,setBusy]=useState(false)
  async function request(path,options={}){const token=await getToken();const response=await fetch(`${api}${path}`,{...options,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(profileToken?{'X-Profile-Token':profileToken}:{}),...options.headers}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`Request failed: ${response.status}`);return data}
  async function loadLibrary(profileId){const items=[];for(let offset=0;;offset+=50){const page=await request(`/api/library?profileId=${encodeURIComponent(profileId)}&limit=50&offset=${offset}`);items.push(...page);if(page.length<50)return items}}
  const enterManage=useReverification(async()=>{const token=await getToken();const response=await fetch(`${api}/api/manage-access`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'}});return response.json()})
  const updateProfile=useReverification(async(id,body)=>{const token=await getToken();const response=await fetch(`${api}/api/profiles/${id}`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json','X-Profile-Token':profileToken},body:JSON.stringify(body)});return response.json()})
  async function openManage(){try{setError('');const result=await enterManage();if(result?.ok)setView('manage')}catch(e){if(e?.name!=='ClerkRuntimeError')setError(e.message||'Password verification was cancelled.')}}
  useEffect(()=>{request('/api/profiles').then(setProfiles).catch(e=>setError(e.message))},[])
  useEffect(()=>{if(profile&&profileToken)Promise.all([loadLibrary(profile.id),request(`/api/progress?profileId=${encodeURIComponent(profile.id)}`),request(`/api/favorites?profileId=${encodeURIComponent(profile.id)}`)]).then(([items,positions,saved])=>{setMedia(items);setProgress(positions);setFavorites(saved.map(item=>item.mediaId))}).catch(e=>setError(e.message))},[profile,profileToken])
  function resetForm(){setForm({name:'',pin:'',isKids:false,removePin:false})}
  function begin(item,action){setError('');if(item.hasPin){setPending({profile:item,action});setPin('')}else unlock(item,'',action)}
  async function unlock(item,enteredPin,action){try{setBusy(true);setError('');const result=await request(`/api/profiles/${item.id}/unlock`,{method:'POST',body:JSON.stringify({pin:enteredPin}),headers:{'X-Profile-Token':''}});setProfileToken(result.token);setPending(null);setPin('');if(action==='edit'){setProfile(item);setForm({name:item.name,pin:'',isKids:item.isKids,removePin:false});setView('edit')}else{setProfile(item);setView('library')}}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function addProfile(event){event.preventDefault();try{setBusy(true);setError('');const created=await request('/api/profiles',{method:'POST',body:JSON.stringify({name:form.name,pin:form.pin,isKids:form.isKids})});setProfiles(current=>[...current,created]);resetForm();setView('manage')}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function saveProfile(event){event.preventDefault();try{setBusy(true);setError('');const saved=await updateProfile(profile.id,{name:form.name,isKids:form.isKids});if(saved?.error)throw new Error(saved.error);let hasPin=form.isKids?false:profile.hasPin;if(!form.isKids&&(form.pin||form.removePin)){const result=await request(`/api/profiles/${profile.id}/pin`,{method:'POST',body:JSON.stringify({pin:form.removePin?'':form.pin})});hasPin=result.hasPin}const updated={...profile,name:form.name.trim(),isKids:form.isKids,hasPin};setProfiles(current=>current.map(item=>item.id===profile.id?updated:item));setProfile(null);setProfileToken('');resetForm();setView('manage')}catch(e){setError(e.message||'Password verification was cancelled.')}finally{setBusy(false)}}
  async function deleteProfile(){try{setBusy(true);setError('');await request(`/api/profiles/${profile.id}`,{method:'DELETE'});setProfiles(current=>current.filter(item=>item.id!==profile.id));setProfile(null);setProfileToken('');resetForm();setView('manage')}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function play(item,startAt=0){try{setError('');setSelected({...item,...await request(`/api/media/${item.id}/play`,{method:'POST',body:JSON.stringify({profileId:profile.id})}),startAt})}catch(e){setError(e.message)}}
  async function saveProgress(event){if(!selected||!profile||!Number.isFinite(event.target.currentTime))return;const positionSeconds=Math.floor(event.target.currentTime),updatedAt=new Date().toISOString();setProgress(current=>[{mediaId:selected.id,positionSeconds,updatedAt},...current.filter(item=>item.mediaId!==selected.id)]);try{await request('/api/progress',{method:'POST',body:JSON.stringify({profileId:profile.id,mediaId:selected.id,positionSeconds})})}catch(e){setError(e.message)}}
  async function toggleFavorite(mediaId){const saved=favorites.includes(mediaId);setFavorites(current=>saved?current.filter(id=>id!==mediaId):[...current,mediaId]);try{await request('/api/favorites',{method:saved?'DELETE':'POST',body:JSON.stringify({profileId:profile.id,mediaId})})}catch(e){setFavorites(current=>saved?[...current,mediaId]:current.filter(id=>id!==mediaId));setError(e.message)}}
  function switchProfile(){setProfile(null);setProfileToken('');setSelected(null);setMedia([]);setProgress([]);setFavorites([]);setError('');setView('select')}
  const profilePicker=<div className="profile-grid">{profiles.map(item=><button className="profile-card" key={item.id} onClick={()=>begin(item,view==='manage'?'edit':'watch')}><span className="avatar-wrap"><Avatar profile={item}/>{item.isKids?<span className="profile-corner" title="Kids profile"><FontAwesomeIcon icon={faChild}/></span>:item.hasPin&&<span className="profile-corner" title="PIN protected"><FontAwesomeIcon icon={faLock}/></span>}{view==='manage'&&<span className="edit-mark"><FontAwesomeIcon icon={faPen}/></span>}</span><span className="profile-name">{item.name}</span></button>)}</div>
  return <main className={view==='library'?'home-page':'profile-shell'}>
    {view==='select'&&<header className="site-header"><Logo/><UserButton/></header>}
    {error&&<p role="alert">{error}</p>}
    {view==='select'&&<section className="profile-stage"><h2>Who's watching?</h2>{profilePicker}<button className="outline-button icon-button" onClick={openManage}><FontAwesomeIcon icon={faUsersGear}/>Manage Profiles</button></section>}
    {view==='manage'&&<section className="profile-stage"><h2>Manage Profiles</h2>{profilePicker}<button className="profile-card add-card" onClick={()=>{resetForm();setError('');setView('create')}}><Avatar add/><span className="profile-name">Add Profile</span></button><div className="stage-actions"><button className="primary-button" onClick={()=>setView('select')}>Done</button></div></section>}
    {view==='create'&&<ProfileForm title="Add Profile" form={form} setForm={setForm} onSubmit={addProfile} onCancel={()=>{resetForm();setError('');setView('manage')}} busy={busy}/>}
    {view==='edit'&&<ProfileForm title={`Edit ${profile.name}`} form={form} setForm={setForm} onSubmit={saveProfile} onCancel={()=>{setProfile(null);setProfileToken('');resetForm();setError('');setView('manage')}} onDelete={deleteProfile} hasPin={profile.hasPin} busy={busy}/>}
    {pending&&<div className="modal-backdrop"><form className="dialog" onSubmit={event=>{event.preventDefault();unlock(pending.profile,pin,pending.action)}}><h3>Enter PIN</h3><p>Enter the four digit PIN for {pending.profile.name}.</p><input autoFocus inputMode="numeric" type="password" maxLength="4" pattern="[0-9]{4}" required value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))} aria-label="Four digit PIN"/><div className="form-actions"><button className="primary-button" type="submit" disabled={busy}>Continue</button><button type="button" onClick={()=>{setPending(null);setPin('');setError('')}}>Cancel</button></div></form></div>}
    {view==='library'&&<Home media={media} progress={progress} favorites={favorites} toggleFavorite={toggleFavorite} profile={profile} selected={selected} setSelected={setSelected} play={play} saveProgress={saveProgress} switchProfile={switchProfile}/>}
  </main>
}

function Home({media,progress,favorites,toggleFavorite,profile,selected,setSelected,play,saveProgress,switchProfile}){
  const[query,setQuery]=useState(''),[genre,setGenre]=useState(''),[section,setSection]=useState('home'),[selectedSeries,setSelectedSeries]=useState(null),[selectedSeason,setSelectedSeason]=useState(null),[infoId,setInfoId]=useState(null)
  useEffect(()=>{window.history.replaceState({kingVideos:true,section:'home',series:null,season:null,info:null},'');const restore=event=>{if(!event.state?.kingVideos)return;setSection(event.state.section);setSelectedSeries(event.state.series||null);setSelectedSeason(event.state.season??null);setInfoId(event.state.info||null)};window.addEventListener('popstate',restore);return()=>window.removeEventListener('popstate',restore)},[])
  const positions=useMemo(()=>new Map(progress.map(item=>[item.mediaId,item.positionSeconds])),[progress])
  const lastProgress=progress.slice().filter(item=>item.positionSeconds>0).sort((a,b)=>String(b.updatedAt||'').localeCompare(String(a.updatedAt||'')))[0]
  const featured=lastProgress&&media.find(item=>item.id===lastProgress.mediaId)
  const filtered=media
  const searchMatches=media.filter(item=>[item.title,item.seriesTitle,...(item.genres||[])].filter(Boolean).some(value=>value.toLowerCase().includes(query.toLowerCase())))
  const continuing=filtered.filter(item=>positions.has(item.id))
  const categories=[...new Set(filtered.map(item=>item.category).filter(Boolean))]
  const tvItems=filtered.filter(item=>/tv|series|show/i.test(item.category))
  const series=useMemo(()=>{const groups=new Map();for(const item of media.filter(item=>/tv|series|show/i.test(item.category)&&item.seriesId)){const group=groups.get(item.seriesId)||[];group.push(item);groups.set(item.seriesId,group)}return groups},[media])
  const tvCards=useMemo(()=>{const grouped=new Map(),standalone=[];for(const item of tvItems){if(!item.seriesId){standalone.push(item);continue}if(!grouped.has(item.seriesId)){const episodes=series.get(item.seriesId)||[item];grouped.set(item.seriesId,{...item,id:`series:${item.seriesId}`,title:item.seriesTitle||item.seriesId,episodeCount:episodes.length,isSeries:true})}}return [...grouped.values(),...standalone]},[tvItems,series])
  const favoriteSet=new Set(favorites)
  const favoriteItems=[...tvCards.filter(item=>item.isSeries&&favoriteSet.has(item.id)),...filtered.filter(item=>favoriteSet.has(item.id))]
  const homeRows=[{title:'Continue Watching',items:continuing},{title:'My List',items:favoriteItems},...categories.slice(0,2).map(category=>({title:category,items:/tv|series|show/i.test(category)?tvCards:filtered.filter(item=>item.category===category)}))]
  const newestFirst=(a,b)=>(b.year||0)-(a.year||0)||a.title.localeCompare(b.title)
  const movieRows=[{title:'Movies · Newest to Oldest',items:filtered.filter(item=>!item.category||/movie/i.test(item.category)).sort(newestFirst)}]
  const tvRows=[{title:'TV Shows · Newest to Oldest',items:tvCards.slice().sort(newestFirst)}]
  const matchingSeries=new Set(searchMatches.map(item=>item.seriesId).filter(Boolean))
  const searchItems=[...tvCards.filter(item=>item.isSeries?matchingSeries.has(item.seriesId):searchMatches.some(match=>match.id===item.id)),...searchMatches.filter(item=>!/tv|series|show/i.test(item.category))]
  const genreItems=[...tvCards.filter(item=>!genre||(series.get(item.seriesId)||[item]).some(episode=>(episode.genres||[]).includes(genre))),...media.filter(item=>!/tv|series|show/i.test(item.category)&&(!genre||(item.genres||[]).includes(genre)))].sort(newestFirst)
  const searchRows=[{title:query?`Results for "${query}"`:'All Titles',items:searchItems}]
  const links=[['home','Home'],['genres','Genres'],['movies','Movies'],['tv','TV']]
  function navigate(path,seriesId=null,season=null,info=null){window.history.pushState({kingVideos:true,section:path,series:seriesId,season,info},'');setSelectedSeries(seriesId);setSelectedSeason(season);setInfoId(info);setSection(path)}
  function openMedia(item){if(item.isSeries)navigate('series',item.seriesId);else play(item)}
  function openInfo(item){if(item.seriesId)navigate('series',item.seriesId);else navigate('info',null,null,item.id)}
  const episodes=(series.get(selectedSeries)||[]).slice().sort((a,b)=>(a.seasonNumber||0)-(b.seasonNumber||0)||(a.episodeNumber||0)-(b.episodeNumber||0)||a.title.localeCompare(b.title))
  const infoItem=media.find(item=>item.id===infoId)
  return <><header className="home-header"><Logo/><nav>{links.map(([path,label])=><button key={path} className={section===path?'active':''} onClick={()=>navigate(path)}>{label}</button>)}<button className={section==='search'?'active':''} onClick={()=>navigate('search')}><FontAwesomeIcon icon={faMagnifyingGlass}/> Search</button></nav><button className="active-profile" onClick={switchProfile} aria-label={`Switch from ${profile.name}`}><Avatar profile={profile}/></button></header>
    {section==='home'&&<><Hero featured={featured} position={lastProgress?.positionSeconds||0} play={play} info={openInfo}/><Shelves rows={homeRows} media={media} positions={positions} favorites={favoriteSet} toggleFavorite={toggleFavorite} onEmptyMyList={()=>navigate('search')} play={openMedia}/></>}
    {section==='genres'&&<GenrePage selected={genre} setSelected={setGenre} items={genreItems} positions={positions} favorites={favoriteSet} toggleFavorite={toggleFavorite} play={openMedia}/>}
    {section==='movies'&&<BrowsePage title="Movies" rows={movieRows} media={media} positions={positions} favorites={favoriteSet} toggleFavorite={toggleFavorite} play={play}/>}
    {section==='tv'&&<BrowsePage title="TV" rows={tvRows} media={media} positions={positions} favorites={favoriteSet} toggleFavorite={toggleFavorite} play={openMedia}/>}
    {section==='series'&&<SeriesPage series={episodes} selectedSeason={selectedSeason} positions={positions} play={play} onBack={()=>window.history.back()} onSelectSeason={season=>navigate('series',selectedSeries,season)}/>}
    {section==='info'&&infoItem&&<InfoPage item={infoItem} saved={favoriteSet.has(infoItem.id)} play={play} toggleFavorite={toggleFavorite} onBack={()=>window.history.back()}/>}
    {section==='search'&&<><section className="search-page"><div className="home-search"><FontAwesomeIcon icon={faMagnifyingGlass}/><input autoFocus aria-label="Search videos" placeholder="Search titles" value={query} onChange={event=>setQuery(event.target.value)}/></div></section><SearchGrid title={searchRows[0].title} query={query} items={searchItems} positions={positions} favorites={favoriteSet} toggleFavorite={toggleFavorite} play={openMedia}/></>}
    {selected&&<section className="player-overlay"><div className="player-bar"><h2>{selected.title}</h2><button className="icon-button" onClick={()=>setSelected(null)}><FontAwesomeIcon icon={faXmark}/>Close</button></div><video controls autoPlay src={selected.url} onLoadedMetadata={event=>{event.currentTarget.currentTime=selected.startAt||0}} onPause={saveProgress} onEnded={saveProgress} onSeeked={saveProgress}/></section>}
  </>
}

function Hero({featured,position,play,info}){return featured&&<section className="hero" style={featured.thumbnailUrl?{'--hero-image':`url("${featured.thumbnailUrl}")`}:undefined}><div className="hero-content"><small>Continue Watching</small><h1>{featured.seriesTitle||featured.title}</h1>{featured.seriesTitle&&<h2>{featured.title}</h2>}<p>{featured.description||'Continue watching on King Videos.'}</p><div><button className="hero-play icon-button" onClick={()=>play(featured,position)}><FontAwesomeIcon icon={faPlay}/>Continue</button><button className="hero-info icon-button" onClick={()=>play(featured,0)}><FontAwesomeIcon icon={faPlay}/>Restart</button><button className="hero-info icon-button" onClick={()=>info(featured)}><FontAwesomeIcon icon={faCircleInfo}/>Info</button></div></div></section>}
function InfoPage({item,saved,play,toggleFavorite,onBack}){return <section className="info-page" style={item.thumbnailUrl?{'--info-image':`url("${item.thumbnailUrl}")`}:undefined}><button className="series-back icon-button" onClick={onBack}><FontAwesomeIcon icon={faArrowLeft}/>Back</button><div className="info-content"><small>{item.category||'Movie'}</small><h1>{item.title}</h1><div className="title-meta">{item.year&&<span>{item.year}</span>}{item.rating&&<span>{item.rating}</span>}{item.durationSeconds&&<span>{Math.round(item.durationSeconds/60)} min</span>}</div><p>{item.description||'Watch on King Videos.'}</p>{item.genres?.length>0&&<div className="genre-list">{item.genres.map(genre=><span key={genre}>{genre}</span>)}</div>}<div className="info-actions"><button className="hero-play icon-button" onClick={()=>play(item,0)}><FontAwesomeIcon icon={faPlay}/>Play</button><button className="hero-info icon-button" onClick={()=>toggleFavorite(item.id)}><FontAwesomeIcon icon={saved?faCheck:faPlus}/>{saved?'In My List':'Add to My List'}</button></div></div></section>}
function Shelves({rows,media,positions,favorites,toggleFavorite,onEmptyMyList,play}){const visible=rows.filter(row=>row.items.length||row.title==='My List');return <div className="shelves">{visible.map(row=><MediaRow key={row.title} title={row.title} items={row.items} positions={positions} favorites={favorites} toggleFavorite={toggleFavorite} onEmptyMyList={onEmptyMyList} play={play}/>)}{!media.length&&<p className="empty-library">No videos yet. Add a video to the catalog to begin.</p>}</div>}
function BrowsePage({title,rows,media,positions,favorites,toggleFavorite,play}){return <><section className="browse-heading"><h1>{title}</h1></section><Shelves rows={rows} media={media} positions={positions} favorites={favorites} toggleFavorite={toggleFavorite} play={play}/></>}

function SearchGrid({title,query,items,positions,favorites,toggleFavorite,play}){const[visibleCount,setVisibleCount]=useState(24),sentinel=React.useRef(null);useEffect(()=>setVisibleCount(24),[query]);useEffect(()=>{const node=sentinel.current;if(!node||visibleCount>=items.length)return;const observer=new IntersectionObserver(entries=>{if(entries[0].isIntersecting)setVisibleCount(count=>Math.min(count+24,items.length))},{rootMargin:'500px'});observer.observe(node);return()=>observer.disconnect()},[visibleCount,items.length]);const visible=items.slice(0,visibleCount);return <section className="search-results"><h2>{title}</h2>{visible.length?<div className="search-grid">{visible.map(item=><article className="shelf-card search-card" key={item.id}><button className="card-main" onClick={()=>play(item)}>{item.thumbnailUrl?<img loading="lazy" src={item.thumbnailUrl} alt=""/>:<span className="poster-placeholder"><FontAwesomeIcon icon={faPlay}/></span>}{positions.has(item.id)&&<span className="watch-progress" style={{'--watched':`${Math.min(92,Math.max(8,positions.get(item.id)/60))}%`}}/>}<strong>{item.title}</strong><small>{item.isSeries?`${item.episodeCount} episodes`:item.category||'Video'}</small></button><button className={`favorite-button${favorites.has(item.id)?' saved':''}`} onClick={()=>toggleFavorite(item.id)} aria-label={`${favorites.has(item.id)?'Remove from':'Add to'} My List`} title={`${favorites.has(item.id)?'Remove from':'Add to'} My List`}><FontAwesomeIcon icon={favorites.has(item.id)?faCheck:faPlus}/></button></article>)}</div>:<p className="empty-search">No titles match your search.</p>}<div className="search-sentinel" ref={sentinel}>{visibleCount<items.length?'Loading more…':''}</div></section>}

function GenrePage({selected,setSelected,items,positions,favorites,toggleFavorite,play}){return <><section className="genre-filters" aria-label="Filter by genre"><button className={!selected?'active':''} onClick={()=>setSelected('')}>All</button>{genres.map(item=><button className={selected===item?'active':''} key={item} onClick={()=>setSelected(item)}>{item}</button>)}</section><SearchGrid title={`${selected||'All Genres'} · Newest to Oldest`} query={`genre:${selected}`} items={items} positions={positions} favorites={favorites} toggleFavorite={toggleFavorite} play={play}/></>}

function SeriesPage({series,selectedSeason,positions,play,onBack,onSelectSeason}){const show=series[0];if(!show)return null;const seasonName=season=>season===0?'Shorts':`Season ${season}`,seasons=[...new Set(series.map(item=>item.seasonNumber??1))].sort((a,b)=>a-b),episodes=selectedSeason===null?[]:series.filter(item=>(item.seasonNumber??1)===selectedSeason);return <section className="series-page"><button className="series-back icon-button" onClick={onBack}><FontAwesomeIcon icon={faArrowLeft}/>{selectedSeason===null?'Back to TV':`Back to ${show.seriesTitle||show.seriesId}`}</button>{selectedSeason===null?<><header className="series-intro">{show.thumbnailUrl&&<img src={show.thumbnailUrl} alt=""/>}<div><small>TV Series</small><h1>{show.seriesTitle||show.seriesId}</h1><p>{show.description}</p><span>{seasons.length} season{seasons.length===1?'':'s'} • {series.length} episodes{show.rating?` • ${show.rating}`:''}</span></div></header><h2>Seasons</h2><div className="season-grid">{seasons.map(season=>{const count=series.filter(item=>(item.seasonNumber??1)===season).length;return <button className="season-card" key={season} onClick={()=>onSelectSeason(season)}>{show.thumbnailUrl?<img src={show.thumbnailUrl} alt=""/>:<span className="poster-placeholder"><FontAwesomeIcon icon={faPlay}/></span>}<span><strong>{seasonName(season)}</strong><small>{count} episode{count===1?'':'s'}</small></span></button>})}</div></>:<><header className="season-heading"><small>{show.seriesTitle||show.seriesId}</small><h1>{seasonName(selectedSeason)}</h1><span>{episodes.length} episode{episodes.length===1?'':'s'}</span></header><div className="episode-grid">{episodes.map(item=><button className="episode-card" key={item.id} onClick={()=>play(item)}>{item.thumbnailUrl?<img src={item.thumbnailUrl} alt=""/>:<span className="poster-placeholder"><FontAwesomeIcon icon={faPlay}/></span>}{positions.has(item.id)&&<span className="watch-progress" style={{'--watched':`${Math.min(92,Math.max(8,positions.get(item.id)/60))}%`}}/>}<span className="episode-copy"><small>{selectedSeason===0?'Short':`Episode ${item.episodeNumber||''}`}</small><strong>{item.title}</strong></span></button>)}</div></>}</section>}

function MediaRow({title,items,positions,favorites,toggleFavorite,onEmptyMyList,play}){const track=React.useRef(null),[edges,setEdges]=useState({start:true,end:true});useEffect(()=>{const node=track.current;if(!node)return;const update=()=>setEdges({start:node.scrollLeft<=2,end:node.scrollLeft+node.clientWidth>=node.scrollWidth-2});update();node.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);return()=>{node.removeEventListener('scroll',update);window.removeEventListener('resize',update)}},[items.length,title]);const scroll=direction=>track.current?.scrollBy({left:direction*track.current.clientWidth*.85,behavior:'smooth'});return <section className="shelf"><h2>{title}</h2>{!edges.start&&<button className="shelf-arrow shelf-arrow-left" onClick={()=>scroll(-1)} aria-label={`Scroll ${title} left`}><FontAwesomeIcon icon={faChevronLeft}/></button>}<div className="shelf-track" ref={track}>{items.map(item=><article id={`media-${item.id}`} className="shelf-card" key={item.id}><button className="card-main" onClick={()=>play(item)}>{item.thumbnailUrl?<img src={item.thumbnailUrl} alt=""/>:<span className="poster-placeholder"><FontAwesomeIcon icon={faPlay}/></span>}{positions.has(item.id)&&<span className="watch-progress" style={{'--watched':`${Math.min(92,Math.max(8,positions.get(item.id)/60))}%`}}/>}<strong>{item.title}</strong><small>{item.isSeries?`${item.episodeCount} episodes`:item.category||'Video'}</small></button><button className={`favorite-button${favorites.has(item.id)?' saved':''}`} onClick={()=>toggleFavorite(item.id)} aria-label={`${favorites.has(item.id)?'Remove from':'Add to'} My List`} title={`${favorites.has(item.id)?'Remove from':'Add to'} My List`}><FontAwesomeIcon icon={favorites.has(item.id)?faCheck:faPlus}/></button></article>)}{title==='My List'&&<button className="empty-list-button" onClick={onEmptyMyList}><span><FontAwesomeIcon icon={faPlus}/></span>Add to My List</button>}</div>{!edges.end&&<button className="shelf-arrow shelf-arrow-right" onClick={()=>scroll(1)} aria-label={`Scroll ${title} right`}><FontAwesomeIcon icon={faChevronRight}/></button>}</section>}

function ProfileForm({title,form,setForm,onSubmit,onCancel,onDelete,hasPin=false,busy}){const[confirmDelete,setConfirmDelete]=useState(false);const change=values=>setForm(current=>({...current,...values}));return <form className="profile-form" onSubmit={onSubmit}><h2>{title}</h2><label>Profile name<input autoFocus maxLength="40" required value={form.name} onChange={e=>change({name:e.target.value})}/></label><label className="check"><input type="checkbox" checked={form.isKids} onChange={e=>change({isKids:e.target.checked,pin:'',removePin:e.target.checked&&hasPin})}/><span><strong><FontAwesomeIcon icon={faChild}/> Kids profile</strong><small>Only videos marked as suitable for kids will appear. Kids profiles cannot have a PIN.</small></span></label>{!form.isKids&&<><label><FontAwesomeIcon icon={faLock}/> {hasPin?'New PIN':'Optional PIN'}<input inputMode="numeric" type="password" maxLength="4" pattern="[0-9]{4}" value={form.pin} disabled={form.removePin} onChange={e=>change({pin:e.target.value.replace(/\D/g,'')})} placeholder={hasPin?'Leave blank to keep current PIN':'Four digits'}/></label>{hasPin&&<label className="check"><input type="checkbox" checked={form.removePin} onChange={e=>change({removePin:e.target.checked,pin:''})}/><span><strong><FontAwesomeIcon icon={faXmark}/> Remove PIN</strong><small>Anyone using this account will be able to open the profile.</small></span></label>}</>}<div className="form-actions"><button className="primary-button" type="submit" disabled={busy}>{busy?'Saving...':'Save'}</button><button type="button" onClick={onCancel}>Cancel</button>{onDelete&&<button className="danger-button icon-button" type="button" onClick={()=>setConfirmDelete(true)} disabled={busy}><FontAwesomeIcon icon={faTrashCan}/>Delete Profile</button>}</div>{confirmDelete&&<div className="modal-backdrop"><div className="dialog confirm-dialog" role="alertdialog" aria-modal="true" aria-labelledby="delete-title"><FontAwesomeIcon className="warning-icon" icon={faTriangleExclamation}/><h3 id="delete-title">Are you sure?</h3><p>Delete <strong>{form.name}</strong>? This will permanently delete the profile and its viewing progress.</p><div className="form-actions"><button type="button" onClick={()=>setConfirmDelete(false)} autoFocus>Cancel</button><button className="danger-button icon-button" type="button" onClick={onDelete} disabled={busy}><FontAwesomeIcon icon={faTrashCan}/>{busy?'Deleting...':'Delete Profile'}</button></div></div></div>}</form>}
createRoot(document.getElementById('root')).render(key&&api?<ClerkProvider publishableKey={key}><SignedOut><main className="signed-out"><Logo/><p>Your private video library.</p><SignInButton mode="modal"><button className="primary-button">Sign in</button></SignInButton></main></SignedOut><SignedIn><App/></SignedIn></ClerkProvider>:<main className="signed-out"><Logo/><p>Set VITE_CLERK_PUBLISHABLE_KEY and VITE_API_URL to configure this app.</p></main>)
