import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ClerkProvider, SignedIn, SignedOut, SignInButton, UserButton, useAuth, useReverification } from '@clerk/clerk-react'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faChild, faCircleInfo, faFaceSmile, faLock, faMagnifyingGlass, faPen, faPlay, faPlus, faTrashCan, faTriangleExclamation, faUsersGear, faXmark } from '@fortawesome/free-solid-svg-icons'
import { HashRouter, NavLink, Navigate, Route, Routes, useNavigate } from 'react-router-dom'
import './style.css'

const key=import.meta.env.VITE_CLERK_PUBLISHABLE_KEY
const api=import.meta.env.VITE_API_URL
const colors=['#e50914','#0f9d8f','#6b38d1','#1773e8','#e67e22','#27952c','#c2185b','#0086a8']
function profileColor(profile){let value=0;for(const char of profile.id)value=(value*31+char.charCodeAt(0))>>>0;return colors[value%colors.length]}
function Avatar({profile,add=false}){return <span className={`avatar${add?' add-avatar':''}`} style={add?undefined:{'--avatar-color':profileColor(profile)}} aria-hidden="true">{add?<FontAwesomeIcon icon={faPlus}/>:<FontAwesomeIcon className="avatar-face" icon={faFaceSmile}/>}</span>}
function Logo(){return <img className="brand-logo" src={`${import.meta.env.BASE_URL}logo-kingflix.png`} alt="Kingflix"/>}

function App(){
  const{getToken}=useAuth()
  const navigate=useNavigate()
  const[profiles,setProfiles]=useState([]),[profile,setProfile]=useState(null),[profileToken,setProfileToken]=useState('')
  const[view,setView]=useState('select'),[pending,setPending]=useState(null),[pin,setPin]=useState('')
  const[form,setForm]=useState({name:'',pin:'',isKids:false,removePin:false})
  const[media,setMedia]=useState([]),[progress,setProgress]=useState([]),[selected,setSelected]=useState(null)
  const[error,setError]=useState(''),[busy,setBusy]=useState(false)
  async function request(path,options={}){const token=await getToken();const response=await fetch(`${api}${path}`,{...options,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(profileToken?{'X-Profile-Token':profileToken}:{}),...options.headers}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`Request failed: ${response.status}`);return data}
  const enterManage=useReverification(async()=>{const token=await getToken();const response=await fetch(`${api}/api/manage-access`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'}});return response.json()})
  const updateProfile=useReverification(async(id,body)=>{const token=await getToken();const response=await fetch(`${api}/api/profiles/${id}`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json','X-Profile-Token':profileToken},body:JSON.stringify(body)});return response.json()})
  async function openManage(){try{setError('');const result=await enterManage();if(result?.ok)setView('manage')}catch(e){if(e?.name!=='ClerkRuntimeError')setError(e.message||'Password verification was cancelled.')}}
  useEffect(()=>{request('/api/profiles').then(setProfiles).catch(e=>setError(e.message))},[])
  useEffect(()=>{if(profile&&profileToken)Promise.all([request(`/api/library?profileId=${encodeURIComponent(profile.id)}`),request(`/api/progress?profileId=${encodeURIComponent(profile.id)}`)]).then(([items,positions])=>{setMedia(items);setProgress(positions)}).catch(e=>setError(e.message))},[profile,profileToken])
  function resetForm(){setForm({name:'',pin:'',isKids:false,removePin:false})}
  function begin(item,action){setError('');if(item.hasPin){setPending({profile:item,action});setPin('')}else unlock(item,'',action)}
  async function unlock(item,enteredPin,action){try{setBusy(true);setError('');const result=await request(`/api/profiles/${item.id}/unlock`,{method:'POST',body:JSON.stringify({pin:enteredPin}),headers:{'X-Profile-Token':''}});setProfileToken(result.token);setPending(null);setPin('');if(action==='edit'){setProfile(item);setForm({name:item.name,pin:'',isKids:item.isKids,removePin:false});setView('edit')}else{setProfile(item);setView('library');navigate('/home')}}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function addProfile(event){event.preventDefault();try{setBusy(true);setError('');const created=await request('/api/profiles',{method:'POST',body:JSON.stringify({name:form.name,pin:form.pin,isKids:form.isKids})});setProfiles(current=>[...current,created]);resetForm();setView('manage')}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function saveProfile(event){event.preventDefault();try{setBusy(true);setError('');const saved=await updateProfile(profile.id,{name:form.name,isKids:form.isKids});if(saved?.error)throw new Error(saved.error);let hasPin=form.isKids?false:profile.hasPin;if(!form.isKids&&(form.pin||form.removePin)){const result=await request(`/api/profiles/${profile.id}/pin`,{method:'POST',body:JSON.stringify({pin:form.removePin?'':form.pin})});hasPin=result.hasPin}const updated={...profile,name:form.name.trim(),isKids:form.isKids,hasPin};setProfiles(current=>current.map(item=>item.id===profile.id?updated:item));setProfile(null);setProfileToken('');resetForm();setView('manage')}catch(e){setError(e.message||'Password verification was cancelled.')}finally{setBusy(false)}}
  async function deleteProfile(){try{setBusy(true);setError('');await request(`/api/profiles/${profile.id}`,{method:'DELETE'});setProfiles(current=>current.filter(item=>item.id!==profile.id));setProfile(null);setProfileToken('');resetForm();setView('manage')}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function play(item){try{setError('');setSelected({...item,...await request(`/api/media/${item.id}/play`,{method:'POST',body:JSON.stringify({profileId:profile.id})})})}catch(e){setError(e.message)}}
  async function saveProgress(event){if(!selected||!profile||!Number.isFinite(event.target.currentTime))return;const positionSeconds=Math.floor(event.target.currentTime);setProgress(current=>[...current.filter(item=>item.mediaId!==selected.id),{mediaId:selected.id,positionSeconds}]);try{await request('/api/progress',{method:'POST',body:JSON.stringify({profileId:profile.id,mediaId:selected.id,positionSeconds})})}catch(e){setError(e.message)}}
  function switchProfile(){setProfile(null);setProfileToken('');setSelected(null);setMedia([]);setProgress([]);setError('');setView('select')}
  const profilePicker=<div className="profile-grid">{profiles.map(item=><button className="profile-card" key={item.id} onClick={()=>begin(item,view==='manage'?'edit':'watch')}><span className="avatar-wrap"><Avatar profile={item}/>{item.isKids?<span className="profile-corner" title="Kids profile"><FontAwesomeIcon icon={faChild}/></span>:item.hasPin&&<span className="profile-corner" title="PIN protected"><FontAwesomeIcon icon={faLock}/></span>}{view==='manage'&&<span className="edit-mark"><FontAwesomeIcon icon={faPen}/></span>}</span><span className="profile-name">{item.name}</span></button>)}</div>
  return <main className={view==='library'?'home-page':'profile-shell'}>
    {view==='select'&&<header className="site-header"><Logo/><UserButton/></header>}
    {error&&<p role="alert">{error}</p>}
    {view==='select'&&<section className="profile-stage"><h2>Who's watching?</h2>{profilePicker}<button className="outline-button icon-button" onClick={openManage}><FontAwesomeIcon icon={faUsersGear}/>Manage Profiles</button></section>}
    {view==='manage'&&<section className="profile-stage"><h2>Manage Profiles</h2>{profilePicker}<button className="profile-card add-card" onClick={()=>{resetForm();setError('');setView('create')}}><Avatar add/><span className="profile-name">Add Profile</span></button><div className="stage-actions"><button className="primary-button" onClick={()=>setView('select')}>Done</button></div></section>}
    {view==='create'&&<ProfileForm title="Add Profile" form={form} setForm={setForm} onSubmit={addProfile} onCancel={()=>{resetForm();setError('');setView('manage')}} busy={busy}/>}
    {view==='edit'&&<ProfileForm title={`Edit ${profile.name}`} form={form} setForm={setForm} onSubmit={saveProfile} onCancel={()=>{setProfile(null);setProfileToken('');resetForm();setError('');setView('manage')}} onDelete={deleteProfile} hasPin={profile.hasPin} busy={busy}/>}
    {pending&&<div className="modal-backdrop"><form className="dialog" onSubmit={event=>{event.preventDefault();unlock(pending.profile,pin,pending.action)}}><h3>Enter PIN</h3><p>Enter the four digit PIN for {pending.profile.name}.</p><input autoFocus inputMode="numeric" type="password" maxLength="4" pattern="[0-9]{4}" required value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))} aria-label="Four digit PIN"/><div className="form-actions"><button className="primary-button" type="submit" disabled={busy}>Continue</button><button type="button" onClick={()=>{setPending(null);setPin('');setError('')}}>Cancel</button></div></form></div>}
    {view==='library'&&<Home media={media} progress={progress} profile={profile} selected={selected} setSelected={setSelected} play={play} saveProgress={saveProgress} switchProfile={switchProfile}/>}
  </main>
}

function Home({media,progress,profile,selected,setSelected,play,saveProgress,switchProfile}){
  const[query,setQuery]=useState('')
  const featured=media[0]
  const positions=useMemo(()=>new Map(progress.map(item=>[item.mediaId,item.positionSeconds])),[progress])
  const filtered=media.filter(item=>item.title.toLowerCase().includes(query.toLowerCase()))
  const continuing=filtered.filter(item=>positions.has(item.id))
  const categories=[...new Set(filtered.map(item=>item.category).filter(Boolean))]
  const homeRows=[{title:'Continue Watching',items:continuing},{title:'My List',items:filtered.slice(0,10)},...categories.slice(0,2).map(category=>({title:category,items:filtered.filter(item=>item.category===category)}))]
  const genreRows=categories.map(category=>({title:category,items:filtered.filter(item=>item.category===category)}))
  const movieRows=[{title:'Movies',items:filtered.filter(item=>!item.category||/movie/i.test(item.category))}]
  const tvRows=[{title:'TV',items:filtered.filter(item=>/tv|series|show/i.test(item.category))}]
  const searchRows=[{title:query?`Results for "${query}"`:'All Titles',items:filtered}]
  const links=[['home','Home'],['genres','Genres'],['movies','Movies'],['tv','TV']]
  return <><header className="home-header"><Logo/><nav>{links.map(([path,label])=><NavLink key={path} to={`/${path}`}>{label}</NavLink>)}<NavLink to="/search"><FontAwesomeIcon icon={faMagnifyingGlass}/> Search</NavLink></nav><button className="active-profile" onClick={switchProfile} aria-label={`Switch from ${profile.name}`}><Avatar profile={profile}/></button></header>
    <Routes>
      <Route path="/home" element={<><Hero featured={featured} play={play}/><Shelves rows={homeRows} media={media} positions={positions} play={play}/></>}/>
      <Route path="/genres" element={<BrowsePage title="Genres" rows={genreRows} media={media} positions={positions} play={play}/>}/>
      <Route path="/movies" element={<BrowsePage title="Movies" rows={movieRows} media={media} positions={positions} play={play}/>}/>
      <Route path="/tv" element={<BrowsePage title="TV" rows={tvRows} media={media} positions={positions} play={play}/>}/>
      <Route path="/search" element={<><section className="search-page"><h1>Search</h1><div className="home-search"><FontAwesomeIcon icon={faMagnifyingGlass}/><input autoFocus aria-label="Search videos" placeholder="Search titles" value={query} onChange={event=>setQuery(event.target.value)}/></div></section><Shelves rows={searchRows} media={media} positions={positions} play={play}/></>}/>
      <Route path="*" element={<Navigate to="/home" replace/>}/>
    </Routes>
    {selected&&<section className="player-overlay"><div className="player-bar"><h2>{selected.title}</h2><button className="icon-button" onClick={()=>setSelected(null)}><FontAwesomeIcon icon={faXmark}/>Close</button></div><video controls autoPlay src={selected.url} onPause={saveProgress} onEnded={saveProgress} onSeeked={saveProgress}/></section>}
  </>
}

function Hero({featured,play}){return featured&&<section className="hero" style={featured.thumbnailUrl?{'--hero-image':`url("${featured.thumbnailUrl}")`}:undefined}><div className="hero-content"><small>{featured.category||'Featured'}</small><h1>{featured.title}</h1><p>{featured.description||'Watch now on King Videos.'}</p><div><button className="hero-play icon-button" onClick={()=>play(featured)}><FontAwesomeIcon icon={faPlay}/>Play</button><button className="hero-info icon-button" onClick={()=>document.getElementById(`media-${featured.id}`)?.scrollIntoView({behavior:'smooth'})}><FontAwesomeIcon icon={faCircleInfo}/>More Info</button></div></div></section>}
function Shelves({rows,media,positions,play}){const visible=rows.filter(row=>row.items.length);return <div className="shelves">{visible.map(row=><MediaRow key={row.title} title={row.title} items={row.items} positions={positions} play={play}/>)}{!media.length&&<p className="empty-library">No videos yet. Add a video to the catalog to begin.</p>}</div>}
function BrowsePage({title,rows,media,positions,play}){return <><section className="browse-heading"><h1>{title}</h1></section><Shelves rows={rows} media={media} positions={positions} play={play}/></>}

function MediaRow({title,items,positions,play}){return <section className="shelf"><h2>{title}</h2><div className="shelf-track">{items.map(item=><button id={`media-${item.id}`} className="shelf-card" key={item.id} onClick={()=>play(item)}>{item.thumbnailUrl?<img src={item.thumbnailUrl} alt=""/>:<span className="poster-placeholder"><FontAwesomeIcon icon={faPlay}/></span>}{positions.has(item.id)&&<span className="watch-progress" style={{'--watched':`${Math.min(92,Math.max(8,positions.get(item.id)/60))}%`}}/>}<strong>{item.title}</strong><small>{item.category||'Video'}</small></button>)}</div></section>}

function ProfileForm({title,form,setForm,onSubmit,onCancel,onDelete,hasPin=false,busy}){const[confirmDelete,setConfirmDelete]=useState(false);const change=values=>setForm(current=>({...current,...values}));return <form className="profile-form" onSubmit={onSubmit}><h2>{title}</h2><label>Profile name<input autoFocus maxLength="40" required value={form.name} onChange={e=>change({name:e.target.value})}/></label><label className="check"><input type="checkbox" checked={form.isKids} onChange={e=>change({isKids:e.target.checked,pin:'',removePin:e.target.checked&&hasPin})}/><span><strong><FontAwesomeIcon icon={faChild}/> Kids profile</strong><small>Only videos marked as suitable for kids will appear. Kids profiles cannot have a PIN.</small></span></label>{!form.isKids&&<><label><FontAwesomeIcon icon={faLock}/> {hasPin?'New PIN':'Optional PIN'}<input inputMode="numeric" type="password" maxLength="4" pattern="[0-9]{4}" value={form.pin} disabled={form.removePin} onChange={e=>change({pin:e.target.value.replace(/\D/g,'')})} placeholder={hasPin?'Leave blank to keep current PIN':'Four digits'}/></label>{hasPin&&<label className="check"><input type="checkbox" checked={form.removePin} onChange={e=>change({removePin:e.target.checked,pin:''})}/><span><strong><FontAwesomeIcon icon={faXmark}/> Remove PIN</strong><small>Anyone using this account will be able to open the profile.</small></span></label>}</>}<div className="form-actions"><button className="primary-button" type="submit" disabled={busy}>{busy?'Saving...':'Save'}</button><button type="button" onClick={onCancel}>Cancel</button>{onDelete&&<button className="danger-button icon-button" type="button" onClick={()=>setConfirmDelete(true)} disabled={busy}><FontAwesomeIcon icon={faTrashCan}/>Delete Profile</button>}</div>{confirmDelete&&<div className="modal-backdrop"><div className="dialog confirm-dialog" role="alertdialog" aria-modal="true" aria-labelledby="delete-title"><FontAwesomeIcon className="warning-icon" icon={faTriangleExclamation}/><h3 id="delete-title">Are you sure?</h3><p>Delete <strong>{form.name}</strong>? This will permanently delete the profile and its viewing progress.</p><div className="form-actions"><button type="button" onClick={()=>setConfirmDelete(false)} autoFocus>Cancel</button><button className="danger-button icon-button" type="button" onClick={onDelete} disabled={busy}><FontAwesomeIcon icon={faTrashCan}/>{busy?'Deleting...':'Delete Profile'}</button></div></div></div>}</form>}
createRoot(document.getElementById('root')).render(key&&api?<ClerkProvider publishableKey={key}><SignedOut><main className="signed-out"><Logo/><p>Your private video library.</p><SignInButton mode="modal"><button className="primary-button">Sign in</button></SignInButton></main></SignedOut><SignedIn><HashRouter><App/></HashRouter></SignedIn></ClerkProvider>:<main className="signed-out"><Logo/><p>Set VITE_CLERK_PUBLISHABLE_KEY and VITE_API_URL to configure this app.</p></main>)
