import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ClerkProvider, SignedIn, SignedOut, SignInButton, UserButton, useAuth, useReverification } from '@clerk/clerk-react'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faArrowLeft, faBaby, faFaceSmile, faLock, faPen, faPlay, faPlus, faTrashCan, faUsersGear, faXmark } from '@fortawesome/free-solid-svg-icons'
import './style.css'

const key=import.meta.env.VITE_CLERK_PUBLISHABLE_KEY
const api=import.meta.env.VITE_API_URL
const colors=['#e50914','#0f9d8f','#6b38d1','#1773e8','#e67e22','#27952c','#c2185b','#0086a8']
function initials(name){return name.trim().split(/\s+/).slice(0,2).map(part=>part[0]).join('').toUpperCase()}
function profileColor(profile){let value=0;for(const char of profile.id)value=(value*31+char.charCodeAt(0))>>>0;return colors[value%colors.length]}
function Avatar({profile,add=false}){return <span className={`avatar${add?' add-avatar':''}`} style={add?undefined:{'--avatar-color':profileColor(profile)}} aria-hidden="true">{add?<FontAwesomeIcon icon={faPlus}/>:<><FontAwesomeIcon className="avatar-face" icon={faFaceSmile}/><span className="avatar-initials">{initials(profile.name)}</span></>}</span>}

function App(){
  const{getToken}=useAuth()
  const[profiles,setProfiles]=useState([]),[profile,setProfile]=useState(null),[profileToken,setProfileToken]=useState('')
  const[view,setView]=useState('select'),[pending,setPending]=useState(null),[pin,setPin]=useState('')
  const[form,setForm]=useState({name:'',pin:'',isKids:false,removePin:false})
  const[media,setMedia]=useState([]),[selected,setSelected]=useState(null),[query,setQuery]=useState('')
  const[error,setError]=useState(''),[busy,setBusy]=useState(false)
  async function request(path,options={}){const token=await getToken();const response=await fetch(`${api}${path}`,{...options,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(profileToken?{'X-Profile-Token':profileToken}:{}),...options.headers}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`Request failed: ${response.status}`);return data}
  const enterManage=useReverification(async()=>{const token=await getToken();const response=await fetch(`${api}/api/manage-access`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'}});return response.json()})
  async function openManage(){try{setError('');const result=await enterManage();if(result?.ok)setView('manage')}catch(e){if(e?.name!=='ClerkRuntimeError')setError(e.message||'Password verification was cancelled.')}}
  useEffect(()=>{request('/api/profiles').then(setProfiles).catch(e=>setError(e.message))},[])
  useEffect(()=>{if(profile&&profileToken)request(`/api/library?profileId=${encodeURIComponent(profile.id)}`).then(setMedia).catch(e=>setError(e.message))},[profile,profileToken])
  function resetForm(){setForm({name:'',pin:'',isKids:false,removePin:false})}
  function begin(item,action){setError('');if(item.hasPin){setPending({profile:item,action});setPin('')}else unlock(item,'',action)}
  async function unlock(item,enteredPin,action){try{setBusy(true);setError('');const result=await request(`/api/profiles/${item.id}/unlock`,{method:'POST',body:JSON.stringify({pin:enteredPin}),headers:{'X-Profile-Token':''}});setProfileToken(result.token);setPending(null);setPin('');if(action==='edit'){setProfile(item);setForm({name:item.name,pin:'',isKids:item.isKids,removePin:false});setView('edit')}else{setProfile(item);setView('library')}}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function addProfile(event){event.preventDefault();try{setBusy(true);setError('');const created=await request('/api/profiles',{method:'POST',body:JSON.stringify({name:form.name,pin:form.pin,isKids:form.isKids})});setProfiles(current=>[...current,created]);resetForm();setView('manage')}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function saveProfile(event){event.preventDefault();try{setBusy(true);setError('');await request(`/api/profiles/${profile.id}`,{method:'POST',body:JSON.stringify({name:form.name,isKids:form.isKids})});let hasPin=profile.hasPin;if(form.pin||form.removePin){const result=await request(`/api/profiles/${profile.id}/pin`,{method:'POST',body:JSON.stringify({pin:form.removePin?'':form.pin})});hasPin=result.hasPin}const updated={...profile,name:form.name.trim(),isKids:form.isKids,hasPin};setProfiles(current=>current.map(item=>item.id===profile.id?updated:item));setProfile(null);setProfileToken('');resetForm();setView('manage')}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function deleteProfile(){if(!window.confirm(`Delete ${profile.name}? Their viewing progress will also be deleted.`))return;try{setBusy(true);setError('');await request(`/api/profiles/${profile.id}`,{method:'DELETE'});setProfiles(current=>current.filter(item=>item.id!==profile.id));setProfile(null);setProfileToken('');resetForm();setView('manage')}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function play(item){try{setError('');setSelected({...item,...await request(`/api/media/${item.id}/play`,{method:'POST',body:JSON.stringify({profileId:profile.id})})})}catch(e){setError(e.message)}}
  async function saveProgress(event){if(!selected||!profile||!Number.isFinite(event.target.currentTime))return;try{await request('/api/progress',{method:'POST',body:JSON.stringify({profileId:profile.id,mediaId:selected.id,positionSeconds:Math.floor(event.target.currentTime)})})}catch(e){setError(e.message)}}
  function switchProfile(){setProfile(null);setProfileToken('');setSelected(null);setMedia([]);setQuery('');setError('');setView('select')}
  const profilePicker=<div className="profile-grid">{profiles.map(item=><button className="profile-card" key={item.id} onClick={()=>begin(item,view==='manage'?'edit':'watch')}><span className="avatar-wrap"><Avatar profile={item}/>{view==='manage'&&<span className="edit-mark"><FontAwesomeIcon icon={faPen}/></span>}</span><span className="profile-name">{item.name}</span><span className="profile-tags">{item.isKids&&<small><FontAwesomeIcon icon={faBaby}/> Kids</small>}{item.hasPin&&<small><FontAwesomeIcon icon={faLock}/> PIN</small>}</span></button>)}</div>
  return <main className={view==='library'?'app-main':'profile-shell'}><header className="site-header"><h1>King Videos</h1><UserButton/></header>{error&&<p role="alert">{error}</p>}
    {view==='select'&&<section className="profile-stage"><h2>Who's watching?</h2>{profilePicker}<button className="outline-button icon-button" onClick={openManage}><FontAwesomeIcon icon={faUsersGear}/>Manage Profiles</button></section>}
    {view==='manage'&&<section className="profile-stage"><h2>Manage Profiles</h2>{profilePicker}<button className="profile-card add-card" onClick={()=>{resetForm();setError('');setView('create')}}><Avatar add/><span className="profile-name">Add Profile</span></button><div className="stage-actions"><button className="primary-button" onClick={()=>setView('select')}>Done</button></div></section>}
    {view==='create'&&<ProfileForm title="Add Profile" form={form} setForm={setForm} onSubmit={addProfile} onCancel={()=>{resetForm();setError('');setView('manage')}} busy={busy}/>}
    {view==='edit'&&<ProfileForm title={`Edit ${profile.name}`} form={form} setForm={setForm} onSubmit={saveProfile} onCancel={()=>{setProfile(null);setProfileToken('');resetForm();setError('');setView('manage')}} onDelete={deleteProfile} hasPin={profile.hasPin} busy={busy}/>}
    {pending&&<div className="modal-backdrop"><form className="dialog" onSubmit={event=>{event.preventDefault();unlock(pending.profile,pin,pending.action)}}><h3>Enter PIN</h3><p>Enter the four digit PIN for {pending.profile.name}.</p><input autoFocus inputMode="numeric" type="password" maxLength="4" pattern="[0-9]{4}" required value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))} aria-label="Four digit PIN"/><div className="form-actions"><button className="primary-button" type="submit" disabled={busy}>Continue</button><button type="button" onClick={()=>{setPending(null);setPin('');setError('')}}>Cancel</button></div></form></div>}
    {view==='library'&&<><nav className="library-nav"><button className="icon-button" onClick={switchProfile}><FontAwesomeIcon icon={faArrowLeft}/>Switch Profile</button><span className="current-profile"><Avatar profile={profile}/><span>{profile.name}{profile.isKids&&<small><FontAwesomeIcon icon={faBaby}/> Kids</small>}</span></span></nav><input className="search" aria-label="Search videos" placeholder="Search videos" value={query} onChange={e=>setQuery(e.target.value)}/>{selected&&<section className="player"><div><h2>{selected.title}</h2><button className="icon-button" onClick={()=>setSelected(null)}><FontAwesomeIcon icon={faXmark}/>Close</button></div><video controls autoPlay src={selected.url} onPause={saveProgress} onEnded={saveProgress} onSeeked={saveProgress}/></section>}<section><h2>Library</h2><div className="media-grid">{media.filter(item=>item.title.toLowerCase().includes(query.toLowerCase())).map(item=><button className="media-card" key={item.id} onClick={()=>play(item)}>{item.thumbnailUrl?<img src={item.thumbnailUrl} alt=""/>:<span className="poster-placeholder"><FontAwesomeIcon icon={faPlay}/></span>}<strong>{item.title}</strong><small>{item.category||'Video'}</small></button>)}</div>{!media.length&&<p>No videos yet. Add a video to the catalog to begin.</p>}</section></>}
  </main>
}
function ProfileForm({title,form,setForm,onSubmit,onCancel,onDelete,hasPin=false,busy}){const change=values=>setForm(current=>({...current,...values}));return <form className="profile-form" onSubmit={onSubmit}><h2>{title}</h2><label>Profile name<input autoFocus maxLength="40" required value={form.name} onChange={e=>change({name:e.target.value})}/></label><label className="check"><input type="checkbox" checked={form.isKids} onChange={e=>change({isKids:e.target.checked})}/><span><strong><FontAwesomeIcon icon={faBaby}/> Kids profile</strong><small>Only videos marked as suitable for kids will appear.</small></span></label><label><FontAwesomeIcon icon={faLock}/> {hasPin?'New PIN':'Optional PIN'}<input inputMode="numeric" type="password" maxLength="4" pattern="[0-9]{4}" value={form.pin} disabled={form.removePin} onChange={e=>change({pin:e.target.value.replace(/\D/g,'')})} placeholder={hasPin?'Leave blank to keep current PIN':'Four digits'}/></label>{hasPin&&<label className="check"><input type="checkbox" checked={form.removePin} onChange={e=>change({removePin:e.target.checked,pin:''})}/><span><strong><FontAwesomeIcon icon={faXmark}/> Remove PIN</strong><small>Anyone using this account will be able to open the profile.</small></span></label>}<div className="form-actions"><button className="primary-button" type="submit" disabled={busy}>{busy?'Saving…':'Save'}</button><button type="button" onClick={onCancel}>Cancel</button>{onDelete&&<button className="danger-button icon-button" type="button" onClick={onDelete} disabled={busy}><FontAwesomeIcon icon={faTrashCan}/>Delete Profile</button>}</div></form>}
createRoot(document.getElementById('root')).render(key&&api?<ClerkProvider publishableKey={key}><SignedOut><main className="signed-out"><h1>King Videos</h1><p>Your private video library.</p><SignInButton mode="modal"><button className="primary-button">Sign in</button></SignInButton></main></SignedOut><SignedIn><App/></SignedIn></ClerkProvider>:<main className="signed-out"><h1>King Videos</h1><p>Set VITE_CLERK_PUBLISHABLE_KEY and VITE_API_URL to configure this app.</p></main>)
