import { readFile, stat } from 'node:fs/promises'
import { basename, resolve } from 'node:path'
import process from 'node:process'

const manifestPath=resolve(process.argv[2]||''),folder=resolve(process.argv[3]||'')
if(!process.argv[2]||!process.argv[3])throw new Error('Usage: node scripts/verify-shorts.mjs <media.json> <video-folder>')
for(const name of ['B2_BOOTSTRAP_KEY_ID','B2_BOOTSTRAP_APPLICATION_KEY','CLOUDFLARE_API_TOKEN','CLOUDFLARE_ACCOUNT_ID'])if(!process.env[name])throw new Error(`${name} is required`)
const manifest=JSON.parse(await readFile(manifestPath,'utf8')),prefix=`movies/${manifest.id}/`,expected=new Map()
for(const item of manifest.items){expected.set(`${prefix}${item.id}/${item.id}.mp4`,(await stat(resolve(folder,item.video))).size);expected.set(`${prefix}${item.id}/${basename(item.thumbnail)}`,(await stat(resolve(folder,item.thumbnail))).size)}
const basic=Buffer.from(`${process.env.B2_BOOTSTRAP_KEY_ID}:${process.env.B2_BOOTSTRAP_APPLICATION_KEY}`).toString('base64'),authResponse=await fetch('https://api.backblazeb2.com/b2api/v4/b2_authorize_account',{headers:{Authorization:`Basic ${basic}`}}),auth=await authResponse.json(),storage=auth.apiInfo.storageApi
async function b2(operation,body){const response=await fetch(`${storage.apiUrl}/b2api/v4/${operation}`,{method:'POST',headers:{Authorization:auth.authorizationToken,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok)throw new Error(`${operation} failed: ${await response.text()}`);return response.json()}
const buckets=await b2('b2_list_buckets',{accountId:auth.accountId,bucketName:process.env.B2_BUCKET||'king-videos'}),bucket=buckets.buckets?.[0],remote=new Map();let nextFileName
do{const page=await b2('b2_list_file_names',{bucketId:bucket.bucketId,prefix,maxFileCount:10000,...(nextFileName?{startFileName:nextFileName}:{})});for(const file of page.files||[])remote.set(file.fileName,file.contentLength);nextFileName=page.nextFileName}while(nextFileName)
const missing=[...expected].filter(([key,size])=>remote.get(key)!==size).map(([key])=>key),unexpected=[...remote.keys()].filter(key=>!expected.has(key))
const headers={Authorization:`Bearer ${process.env.CLOUDFLARE_API_TOKEN}`,'Content-Type':'application/json'},databaseName=process.env.D1_DATABASE||'king-videos-prod',dbs=await (await fetch(`https://api.cloudflare.com/client/v4/accounts/${process.env.CLOUDFLARE_ACCOUNT_ID}/d1/database`,{headers})).json(),database=dbs.result?.find(item=>item.name===databaseName),ids=manifest.items.map(item=>item.id),placeholders=ids.map(()=>'?').join(','),query=await (await fetch(`https://api.cloudflare.com/client/v4/accounts/${process.env.CLOUDFLARE_ACCOUNT_ID}/d1/database/${database.uuid}/query`,{method:'POST',headers,body:JSON.stringify({sql:`SELECT COUNT(*) records,SUM(CASE WHEN description<>'' THEN 1 ELSE 0 END) descriptions,SUM(CASE WHEN duration_seconds>0 THEN 1 ELSE 0 END) durations,SUM(CASE WHEN category='short' THEN 1 ELSE 0 END) shorts FROM media WHERE id IN (${placeholders})`,params:ids})})).json(),databaseCounts=query.result?.[0]?.results?.[0]
const result={manifestItems:manifest.items.length,expectedObjects:expected.size,remoteObjects:remote.size,missingOrWrongSize:missing,unexpected,database:databaseCounts};console.log(JSON.stringify(result,null,2));if(missing.length||unexpected.length||Number(databaseCounts?.records)!==manifest.items.length)process.exitCode=2
